language: php
php:
- '7.1'
- '7.0'
- '5.6'
- '5.5'
- '5.4'

before_script:
- |
  if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]] || [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
        wget https://phar.phpunit.de/phpunit-5.7.phar -O /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit
  else
        wget https://phar.phpunit.de/phpunit-4.8.phar -O /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit
  fi
  wget "https://github.com/codeclimate/php-test-reporter/releases/download/$TEST_REPORTER_RELEASE/codeclimate-test-reporter.phar" -O /usr/local/bin/test-reporter && chmod +x /usr/local/bin/test-reporter

script: phpunit --coverage-clover clover.xml

after_success:
- test-reporter -coverage-report=clover.xml