language: php
php:
- '7.1'
- '7.0'
- '5.6'
- '5.5'
- '5.4'

before_script:
- |
  if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]] || [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
        sudo wget https://phar.phpunit.de/phpunit-5.7.phar -O /usr/local/bin/phpunit && sudo chmod +x /usr/local/bin/phpunit
  else
        sudo wget https://phar.phpunit.de/phpunit-4.8.phar -O /usr/local/bin/phpunit && sudo chmod +x /usr/local/bin/phpunit
  fi
  composer global require codeclimate/php-test-reporter --dev
script:
- phpunit --coverage-clover clover.xml
- bash debug.sh

after_success:
- test-reporter -coverage-report=clover.xml