language: php
php:
- '7.1'
- '7.0'
- '5.6'
- '5.5'
- '5.4'

before_script:
- |
  if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
        composer global require "phpunit/phpunit=5.6.*"
  else
        composer global require "phpunit/phpunit=4.8.*"
  fi

script: phpunit --coverage-clover clover.xml

after_success:
- test-reporter -coverage-report=clover.xml